# Cmake >= 3.13 required

language: python
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

addons:
  apt:
    packages:
    - gfortran

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls
  - os: linux
    language: minimal
    addons:
      apt:
        packages:
        - gfortran
        - octave
    before_install:
    - git clone https://github.com/scivision/cmake-utils
    - cd $TRAVIS_BUILD_DIR/cmake-utils
    - bash cmake_setup.sh
    - export PATH=$HOME/.local/cmake-3.13.4-Linux-x86_64/bin/:$PATH
    - cd $TRAVIS_BUILD_DIR
    install: octave-cli matlab/setup_iri2016.m
    script: octave-cli tests/test_iri2016.m
#  - os: osx
#    language: sh
#    before_install:
#    - brew install gcc
#    - brew upgrade cmake
#    install: pip3 install -e .[tests]
#  - os: windows
#    language: sh
#    before_install:
#    - choco install python3
#    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
#  - os: windows
#    language: sh
#    before_install: choco install octave.portable
#    install: octave-cli matlab/setup_iri2016.m
#    script: octave-cli tests/test_iri2016.m


install: pip install -e .[tests]

script: pytest -rsv
