# wait with octave tests till github actions migration
variables:
  CI: true

stages:

- stage: SyntaxChecks
  jobs:

  - job: PEP8_MyPy_Python37
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: pip install -e .[lint]
      displayName: 'Dev install'
    - script: flake8
      displayName: PEP8
    - script: mypy .
      displayName: Type Check

- stage: IntegrationTests
  jobs:

  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        addToPath: true
    - script: |
        python -m pip install meson
        curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
        sudo unzip ninja-linux.zip -d /usr/local/bin/
      displayName: 'setup Meson'
    - script: sudo apt install -yq --no-install-recommends gfortran
      displayName: 'Install Prereqs'
    - script: pip install -e .[tests]
      displayName: 'Build Python'
    - script: pytest -r a -v
      displayName: 'PyTest'

  - job: MacOS
    pool:
      vmImage: macOS-latest

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        addToPath: true
    - script: |
        brew install gcc ninja
        pip install meson
      displayName: 'Install Prereqs'
    - script: pip install -e .[tests]
      displayName: 'Build Python'
    - script: pytest -r a -v
      displayName: 'PyTest'

  - job: WindowsMinGW
    pool:
      vmImage: windows-latest

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        addToPath: true
    - script: |
        cinst -y mingw ninja
        pip install meson
      displayName: 'Install Prereqs'
    - script: pip install -e .[tests]
      displayName: 'Build Python'
    - script: pytest -r a -v
      displayName: 'PyTest'


- stage: CoverageTests

  jobs:
  - job: CoverageOctave
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        python -m pip install meson
        curl -Ls https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip -o ninja-linux.zip
        sudo unzip ninja-linux.zip -d /usr/local/bin/
      displayName: 'setup Meson'
    - script: sudo apt install -yq --no-install-recommends gfortran
      displayName: 'Install Prereqs'
    - script: pip install -e .[tests]
      displayName: 'Dev install'
    - script: pytest --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
      displayName: Coverage

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops#publish-code-coverage-results
    - task: PublishCodeCoverageResults@1
      condition: succeeded()
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
